development:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: app@caregaroo.com
  :password: 4MdRA+3[
  :enable_starttls_auto: true
test:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: app@caregaroo.com
  :password: 4MdRA+3[
  :enable_starttls_auto: true
production:
  :address: smtp.gmail.com
  :port: 587
  :authentication: plain
  :user_name: app@caregaroo.com
  :password: 4MdRA+3[
  :enable_starttls_auto: true