default:
    host: localhost
    post: 6379
development:    
    db: 0
    # namespace: caregaroo_dev
test:    
    db: 1
    # namespace: caregaroo_test
production:    
    db: 2
    # namespace: caregaroo_prod
heroku:
    host:herring.redistogo.com
    port:9294 
    password:686749979ff3d80018c958ef2204cdc8
