do_daily_activity_emails:
  # every: 20s
  cron: "0 17 * * *"
  class: DailyActivityEmails
  args:
  description: Runs the perform method in MyJob

# do_nightly_activity_emails:
#   cron: "* 17 * * *"
#   class: DailyActivityEmails
#   args:
#   description: Runs the perform method in MyJob